name: cheon
description: A Smart Study Planner.

version: 0.0.1+1

environment:
  sdk: ">=2.8.0 <2.17.0"

dependencies:
  flutter:
    sdk: flutter

  ################################ UI PACKAGES #################################
  font_awesome_flutter: ^8.11.0
  flutter_spinkit: ^4.1.2+1
  dotted_border: ^1.0.6
  sticky_headers: ^0.1.8+1
  flutter_markdown: ^0.5.2
  flutter_svg: ^0.18.1
  animations: ^1.1.2
  flutter_html: ^1.1.0

  ########################## DATA PERSISTENCE PACKAGES #########################
  hive: ^1.4.4+1
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  path_provider: ^1.6.22

  ############################### OTHER PACKAGES ###############################
  provider: ^4.3.3
  url_launcher: ^5.7.2
  package_info: ^0.4.3
  share: ^0.6.5+4
  quick_actions: ^0.4.0+10
  kiwi: ^2.1.1
  timeago: ^2.0.28
  json_annotation: ^3.1.0
  rxdart: ^0.24.1
  flutter_local_notifications: ^1.4.4+4
  uuid: ^2.2.2
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0
  device_calendar: ^3.1.0
  equatable: ^1.2.5
  wiredash: ^0.4.0
  flutter_interactive_keyboard: ^0.1.3
  rate_my_app: ^0.7.2
  import_sorter: ^4.2.2
  in_app_review: ^1.0.4
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  mockito: ^4.1.3
  build_runner: ^1.10.2
  kiwi_generator: ^2.1.1
  moor_generator: ^3.4.1
  json_serializable: ^3.5.0
  freezed: ^0.12.7

dependency_overrides:
  flutter_svg: ^0.18.1
  collection: ^1.15.0
  characters: ^1.2.0
  typed_data: ^1.3.0
  vector_math: ^2.1.0
  matcher: ^0.12.10
  meta: ^1.7.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/logo.png"
  image_path_ios: "assets/logo/logo_filled.jpg"

flutter_native_splash:
  image: assets/icons/logo_filled.jpg
  color: "4caf50"
  android: false

import_sorter:
  ignored_files:
    - \/*.g.dart/

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Medium.ttf
    - family: CheonIcons
      fonts:
        - asset: fonts/CheonIcons.ttf
