name: Flutter Build
on: [push, pull_request]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter 1.22.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.22.6'
      - name: Install dependencies from lock file
        run: flutter pub get --offline || flutter pub get
      - name: Build iOS
        run: flutter build ios --no-codesign

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Install Flutter 1.22.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.22.6'
      - name: Install dependencies from lock file
        run: flutter pub get --offline || flutter pub get
      - name: Build Android
        run: flutter build apk --release
